(defun load-org-mode ()
  (add-to-list 'load-path (expand-file-name "./org-mode/lisp"))
  (add-to-list 'load-path (expand-file-name "."))
  ;; Note: Org uses lower version when org-mode/contrib/lisp is on the load path
  (org-babel-do-load-languages 'org-babel-load-languages '((emacs-lisp . t) (shell . t) (python . t)))
  (setq org-confirm-babel-evaluate nil)
  (message "Running tests against org-version: %s" (org-version)))

(defun load-async ()
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")))
  (setq package-user-dir (expand-file-name "./elpa"))
  (require 'package)
  (package-initialize)
  (package-refresh-contents)
  (package-install 'async)
  (require 'async)
  (message "Running tests against async-version: %s" (package-desc-version (cadr (assq 'async package-alist)))))

(load-org-mode)
(load-async)
(load "test-ob-async.el")
(add-to-list 'org-ctrl-c-ctrl-c-hook 'ob-async-org-babel-execute-src-block)
(ert-run-tests-batch-and-exit)
